---
jobs:
  - name: deploy-ml-to-pws
    plan:
    - get: mlb-ml-repo
      trigger: true
    - put: deploy-to-cf
      params:
        path: mlb-ml-repo
        manifest: mlb-ml-repo/manifest.yml
  - name: run-ml
    plan:
    - get: mlb-ml-repo
      trigger: false
      passed: [deploy-ml-to-pws]
    - task: run-ml-script
      file: mlb-ml-repo/ci/tasks/run_machine_learning.yml
resources:
  - name: mlb-ml-repo
    type: git
    source:
      uri: https://github.com/fire-ants/mlb-machine-learning.git
      branch: {{BRANCH}}
      private_key: {{GIT_PRIVATE_KEY}}

  - name: deploy-to-cf
    type: cf
    source:
      api: {{PWS_API}}
      username: {{PWS_USER}}
      password: {{PWS_PASS}}
      organization: {{PWS_ORG}}
      space: {{PWS_SPACE}}
      skip_cert_check: true
